/*
    You are given a keypad (as shown in the diagram) and an array arr[ ] containing digits,
    your task is to list all possible words in any order which can be generated by pressing numbers in arr[] sequentially.

    Note: Number 0 and 1 do not map to any letters.
    You can return the words in any order, the driver code will print them in sorted order.

    Examples :

    Input: arr[] = [2, 3]
    Output: [ad, ae, af, bd, be, bf, cd, ce, cf]
    Explanation: When we press 2 and 3 total 3 x 3 = 9 possible words formed.

    Input: arr[] = [2]
    Output: [a, b, c]
    Explanation: When we press 2 total 3 possible words formed.

    Constraints:
    1 ≤ arr.size() ≤ 9
    0 ≤ arr[i] ≤ 9
*/

#include <iostream>
#include <vector>
#include <string>
using namespace std;

class Solution {
public:
    // Keypad mapping for digits 0-9, * and #
    string keypad[12] = {
        "", "", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz", "", ""
    };

    // Helper function to perform backtracking
    void backtrack(int idx, vector<int>& arr, string& current, vector<string>& result) {
        // If we have processed all digits, add the current word to result
        if (idx == arr.size()) {
            result.push_back(current);
            return;
        }
        
        // Get the corresponding letters for the current digit
        string letters = keypad[arr[idx]];
        
        // If the digit does not map to any letters (e.g., *, #, 0, or 1), skip it
        if (letters.empty()) {
            backtrack(idx + 1, arr, current, result);
            return;
        }

        // Try each letter for the current digit
        for (char ch : letters) {
            current.push_back(ch);  // Add the letter to the current word
            backtrack(idx + 1, arr, current, result);  // Recurse with the next digit
            current.pop_back();  // Backtrack, remove the last character
        }
    }

    // Main function to return all possible words
    vector<string> possibleWords(vector<int>& arr) {
        vector<string> result;
        string current = "";
        backtrack(0, arr, current, result);  // Start the backtracking process
        return result;
    }
};

int main() {
    Solution sol;
    
    // Test Case 1: Input array [2, 3]
    vector<int> arr1 = {2, 3};
    vector<string> result1 = sol.possibleWords(arr1);
    
    cout << "Possible words formed from digits 2 and 3:\n";
    for (const string& word : result1) {
        cout << word << " ";
    }
    cout << endl;

    // Test Case 2: Input array [2]
    vector<int> arr2 = {2};
    vector<string> result2 = sol.possibleWords(arr2);
    
    cout << "Possible words formed from digit 2:\n";
    for (const string& word : result2) {
        cout << word << " ";
    }
    cout << endl;

    // Test Case 3: Input array with '*' and '#' digits
    vector<int> arr3 = {2, 3, 1, 7, 8, 0};
    vector<string> result3 = sol.possibleWords(arr3);
    
    cout << "Possible words formed from digits 2, 3, 1, 7, 8, 0:\n";
    for (const string& word : result3) {
        cout << word << " ";
    }
    cout << endl;

    return 0;
}
